#!/usr/bin/env python3
"""Regenerate the dependency lockfiles (requirements.lock, requirements-build.lock).

Uses `uv pip compile --universal --generate-hashes` so a single lock serves
every platform. pip-tools would resolve for the compiling platform only and
silently drop e.g. uvloop (uvicorn[standard]'s Linux-only extra) when run on
Windows; uv's --universal mode keeps the environment markers instead.

Run after editing any requirements*.txt, then review the lock diff:

    python scripts/lock_deps.py

CI installs the locks with `pip install --require-hashes`, which is why the
hashes matter: a tampered or swapped wheel fails the install outright.
uv itself is installed ad hoc (not pinned) -- the compile is a dev-time
action whose output is always reviewed as a diff before committing.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# (output lockfile, source .txt inputs) -- order matters for test_lock_coverage.
LOCKS: list[tuple[str, list[str]]] = [
    ("requirements.lock", ["requirements.txt", "requirements-web.txt"]),
    (
        "requirements-build.lock",
        ["requirements.txt", "requirements-web.txt", "requirements-build.txt"],
    ),
]


def compile_args(output: str, inputs: list[str]) -> list[str]:
    """The uv invocation for one lockfile (separate function so tests can pin
    the flags without running uv). Relative paths + cwd=ROOT keep the
    autogenerated header identical no matter which machine regenerates."""
    return [
        sys.executable, "-m", "uv", "pip", "compile",
        "--universal", "--generate-hashes",
        "--python-version", "3.13",
        "--output-file", output,
        *inputs,
    ]


def main() -> None:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "--quiet", "uv"])
    for output, inputs in LOCKS:
        print(f"compiling {output} <- {', '.join(inputs)}")
        subprocess.check_call(compile_args(output, inputs), cwd=ROOT)
    print("done -- review the lock diff before committing")


if __name__ == "__main__":
    main()
